# -*- coding: utf-8 -*-
"""DAUP_Week-5_Programs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSb36JpXVtnA2El7ciboghmlVovC41bk
"""

#Create a series of plots to analyze a given dataset.
import pandas as pd
import matplotlib.pyplot as plt

# Load the Iris dataset directly from an online source (CSV)
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

# Display first few rows
print(df.head())

#Histogram — to see data distribution
plt.figure(figsize=(8,5))
df['sepal_length'].hist(bins=15, color='skyblue', edgecolor='black')
plt.title('Distribution of Sepal Length')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

#Boxplot — to check spread and outliers
plt.figure(figsize=(8,5))
df.boxplot(column=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
plt.title('Boxplot of Iris Features')
plt.ylabel('cm')
plt.show()

#Scatter Plot — relationship between two features
plt.figure(figsize=(8,5))
plt.scatter(df['sepal_length'], df['petal_length'], color='orange')
plt.title('Sepal Length vs Petal Length')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Petal Length (cm)')
plt.grid(True)
plt.show()


#Bar Plot — average petal length by species
avg_petal = df.groupby('species')['petal_length'].mean()
plt.figure(figsize=(8,5))
avg_petal.plot(kind='bar', color=['lightgreen', 'lightcoral', 'lightskyblue'])
plt.title('Average Petal Length by Species')
plt.xlabel('Species')
plt.ylabel('Average Petal Length (cm)')
plt.show()

#Line Plot — compare sepal length trend (sample-wise)
plt.figure(figsize=(8,5))
plt.plot(df['sepal_length'], label='Sepal Length', color='purple')
plt.title('Sepal Length Trend')
plt.xlabel('Sample Index')
plt.ylabel('Sepal Length (cm)')
plt.legend()
plt.grid(True)
plt.show()

#Generate a subplot layout with various plot types (scatter, line, bar).

import numpy as np
import matplotlib.pyplot as plt

# Sample data
x = np.linspace(0, 10, 50)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = x ** 2

# Create subplots
fig, axs = plt.subplots(1, 3, figsize=(15, 4))

# Scatter plot
axs[0].scatter(x, y1, color='r')
axs[0].set_title('Scatter Plot')

# Line plot
axs[1].plot(x, y2, color='g')
axs[1].set_title('Line Plot')

# Bar plot
axs[2].bar(np.arange(5), [10, 20, 15, 30, 25], color='b')
axs[2].set_title('Bar Plot')

plt.tight_layout()
plt.show()

#Visualize time-series data and customize axis labels and date formats.

import pandas as pd
import matplotlib.pyplot as plt

# Create time series data
dates = pd.date_range('2023-01-01', periods=100)
data = pd.Series(range(100), index=dates)

# Plot time series
plt.figure(figsize=(10, 5))
plt.plot(data, color='purple', linewidth=2)
plt.title('Time Series Data')
plt.xlabel('Date')
plt.ylabel('Value')

# Customize date format
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Generate sample 3D data
x = np.linspace(-1, 1, 100)
y = np.linspace(-1, 1, 100)
X, Y = np.meshgrid(x, y)
Z = X**2 + Y**2

# Create a 3D surface plot
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection="3d")
ax.plot_surface(X, Y, Z, cmap="viridis")

# Customize axis labels
ax.set_xlabel("X")
ax.set_ylabel("Y")
ax.set_zlabel("Z")